indent_type = "Spaces"
indent_width = 2
column_width = 120

# Optional, supported knobs:
quote_style = "AutoPreferDouble"   # or "AutoPreferSingle"
call_parentheses = "Always"        # or "None"/"NoSingleString"
